# Include variables based on the distribution
- name: Include task for {{ ansible_distribution }}
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  tags: install

- name: Include task configure haproxy config file
  ansible.builtin.include_tasks: "configure.yml"
  tags: configure
