# https://haproxy.debian.net/#distribution=Ubuntu&release=noble&version=2.9
- name: Block install
  tags: install
  block:
    - name: Set unsupported if HAProxy version is unsupported OS
      ansible.builtin.set_fact:
        haproxy_unsupported: true
      when:
        - haproxy_major_version == "3.1"
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_version is version('24.04', '<')

    - name: Set unsupported condition if Ubuntu < 20.04
      ansible.builtin.set_fact:
        ubuntu_unsupported: true
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_version is version('20.04', '<')

    - name: Show warning if Ubuntu version unsupported
      ansible.builtin.debug:
        msg: "Playbook is not supported on {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: ubuntu_unsupported | default(false)

    - name: End play if Ubuntu version is unsupported
      ansible.builtin.meta: end_play
      when: ubuntu_unsupported | default(false)

    - name: Show warning if HAProxy version is unsupported
      ansible.builtin.debug:
        msg: "HAProxy {{ haproxy_major_version }} is not supported on {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: haproxy_unsupported | default(false)

    - name: End play if HAProxy version is unsupported
      ansible.builtin.meta: end_play
      when: haproxy_unsupported | default(false)

    - name: Install software-properties-common
      ansible.builtin.apt:
        name: software-properties-common
        update_cache: true
        install_recommends: false

    - name: Add haproxy stable repository from PPA
      ansible.builtin.apt_repository:
        repo: "{{ haproxy_repository | default(__haproxy_repository) }}"

    - name: Install haproxy
      ansible.builtin.apt:
        name: haproxy={{ haproxy_version | default(__haproxy_version) }}
        update_cache: true
